# Dictionary

In [2]:
student = {'name' : 'adjie' , 'age' : 18}

In [3]:
employe = {'cto' : {'name' : 'adjie' , 'age' : 18}}

In [4]:
print(student['name'])

adjie


In [5]:
student = dict(name='caput', age =21)

Delete

In [6]:
del student['age']

In [7]:
print(student)

{'name': 'caput'}


# Tuple

In [8]:
people = ('adjie', ('kode', 'random'))
print(people)

('adjie', ('kode', 'random'))


In [1]:
# while True:
#     print('Print Ctrl-C to stop me')
#     break

In [2]:
message = "spam"
while message != '':
    print(message, end=' ')
    message = message[1:]

spam pam am m 

In [6]:
a = 0
b = 13
while a < b:
    print(a, end=' ')
    a = a + 1
# break untuk keluar dari loop / ke else
# continue kembali ke blok keatas lagi
# pass tidak melakukan apapun

0 1 2 3 4 5 6 7 8 9 10 11 12 

In [7]:
# while test:
#     statements
#     if test: break
#     if test: continue
# else:
#     statements

In [8]:
while True:
    name = input("Enter Name: ")
    if name == 'stop' : break
    age = input("enter age: ")
    print('hello', name,'=>', int(age)** 2)

hello adjie => 400
hello adjie => 44100


# For

In [1]:
for word in ['adjie', 'raka', 'hary']:
    print(word, end='\n')

adjie
raka
hary


In [2]:
sum = 0
for i in [1,2,3,4]:
    sum = sum + i
sum

10

In [3]:
prod = 1
for item in [1,2,3,4]: prod *= item
prod

24

In [4]:
text = 'kopi adjie'
words = ('is', 'great', 'coffee')
for chara in text: print (chara, end='\n')

k
o
p
i
 
a
d
j
i
e


In [6]:
for word in words: print(word, end='...')

is...great...coffee...

Patern Matching

In [7]:
coor = [(1,2), (3,4), (5,6)]
for (x,y)in coor: print (x,y)

1 2
3 4
5 6


In [8]:
x = 0
while (x < 100):
    x += 2
print(x)

100


# If

In [9]:
if 1:
    print('true')

true


1 adalah true secara default

In [10]:
if not 1:
    print('true')
else:
    print('false')

false


In [11]:
age = input('enter ur age')
if int(age)* 365 > 20000:
    print('time to retire')
elif int(age) * 365 > 10000:
    print('lots of time left')
else:
    print('time to get started')

lots of time left


In [12]:
user_age = input('enter ur age: ')
age = int(user_age) * 365

if age >= 9490:
    print('your a jedi master now. go learn from master yodaa')
elif age >= 8395 and age < 9490:
    print('becoming jedi knight')
else: 
    print('your a young padawan')

your a young padawan


# Function

In [14]:
def add(a, b):
    return a + b

In [15]:
add(5,7)

12

In [16]:
add_things = add(5,7)

In [18]:
print(add_things)

12


jika tidak return

In [19]:
def add_and_print(a,b):
    print(a + b)

In [20]:
add_and_print(5,5)

10


In [30]:
x = add_and_print(5,5)

10


In [31]:
print(x)

None


In [32]:
def intersection(first_word, second_word):
    result = []
    for x in first_word:
        if x in second_word:
            result.append(x)
    return result

In [33]:
word1 = 'spam'
word2  = 'scam'
char_of_intersect = intersection(word1 , word2)
print(char_of_intersect)

['s', 'a', 'm']


# Modules & built in function

# built in funtion

abs menjadikan nilai mutlak

In [35]:
print(abs(-123))

123


Mengecek Type Data

In [36]:
number  = [1,2,3]
print(isinstance(number, list))

True


In [37]:
print(isinstance(number, dict))

False


In [38]:
numbers = [1,2,3,4,5,6]
print(max(numbers))

6


In [39]:
print(min(numbers))

1


In [40]:
alphas = ['a', 'b', 'c']
print(max(alphas))

c


In [41]:
languages = ['py', 'js', 'go', 'c']
print(languages.index('go'))

2


In [44]:
languages = ['py', 'js', 'go', 'c']
languages.sort()
print(languages)

['c', 'go', 'js', 'py']


In [45]:
name = 'adjie'
print(name)

adjie


In [46]:
name.replace('j', 'z')

'adzie'

In [47]:
name.capitalize()

'Adjie'

# modules

import mengambil modul secara keseluruah

from bisa mengambil sebagian dari sebuah modul

In [49]:
import b
b.logger('calling from a.py')

Log:  calling from a.py


In [50]:
import math
print(math.factorial(3))

6


kita ketik from untuk tidak menulis b. lagi

In [51]:
from b import logger
logger('calling form adjie')

Log:  calling form adjie


In [52]:
from math import factorial
from datetime import datetime

print(factorial(3))
print(datetime.now())

6
2023-04-18 17:50:34.243246


# Packages

In [1]:
import requests

In [2]:
r = requests.get('https://api.github.com/events')

In [4]:
print(r.status_code)
# output 200 berarti sudah ter-load

200


Quiz

In [1]:
def outerFun(a,b):
    def innerFun(c,d):
        return c + d
    return innerFun(a,b)
res = outerFun(5,10) 
print(res)

15


In [ ]:
# cara membuat funtion
# def myFunction():

# Bonus Chapter

In [10]:
import numpy as np

In [12]:
height = [1.75, 1.65, 1.8, 1.81, 1.69]
weight = [66.4, 49.22, 66.7, 88.3, 65.3]
np_height = np.array(height)
np_weight = np.array(weight)

bmi = np_weight / np_height ** 2
print(bmi)

[21.68163265 18.07897153 20.58641975 26.95277922 22.86334512]


numpy bisa mengkonversi type data

In [13]:
mixed_array = np.array([1.0, 'is', True])
print(mixed_array)

['1.0' 'is' 'True']


In [14]:
numlist = [1,2,3]
nparray = np.array([1,2,3])
numlist + numlist

[1, 2, 3, 1, 2, 3]

In [15]:
bmi > 24

array([False, False, False,  True, False])

In [16]:
bmi[bmi > 24]

array([26.95277922])

mari menggenerate BMI dengan data 5000

In [17]:
import numpy as np

In [18]:
height = np.round(np.random.normal(1.75, 0.2, 5000), 2)
height

array([2.29, 1.84, 1.87, ..., 1.62, 1.7 , 1.73])

review code:
round = untuk pembulatan bilangan (2 dijit)
random normal = nilai acak (dengan nilai rata rata 1.75)
deviasi = (2)
column_stack = 2 kolom 5000 baris

In [19]:
len(height)

5000

In [20]:
weight = np.round(np.random.normal(60.32, 15, 5000), 2)
weight

array([74.8 , 66.94, 66.09, ..., 82.57, 88.06, 87.57])

In [21]:
len(weight)

5000

In [23]:
np_city = np.column_stack((height, weight))

In [24]:
# mencari nilai rata rata (mean)
np.mean(np_city[:,0])

1.7460559999999998

In [25]:
# mencari nilai median
np.median(np_city[:,0])

1.74

In [26]:
# mencari nilai standard deviasi
np.std(np_city[:,0])

0.20242757930677333

# Numpy Array 2D

In [27]:
import numpy as np

In [28]:
height = np.array([1.75, 1.68, 1.8])
weight = np.array([66.4, 49.22, 66.3])

In [30]:
type(height)
# n dimensional array

numpy.ndarray

In [31]:
np_2d = np.array([[1.75, 1.68, 1.8], [66.4, 49.22, 66.3]])

In [32]:
np_2d

array([[ 1.75,  1.68,  1.8 ],
       [66.4 , 49.22, 66.3 ]])

In [33]:
np_2d.shape

(2, 3)

In [34]:
# subsetting
np_2d[0]

array([1.75, 1.68, 1.8 ])

In [35]:
np_2d[0][2]

1.8

In [39]:
# subsetting lanjut
np_2d

array([[ 1.75,  1.68,  1.8 ],
       [66.4 , 49.22, 66.3 ]])

In [40]:
np_2d[:,1:3]

array([[ 1.68,  1.8 ],
       [49.22, 66.3 ]])

In [41]:
np_2d[1,:]

array([66.4 , 49.22, 66.3 ])