In [9]:
# pip install matplotlib

In [2]:
import numpy as np
import statistics
import math
import scipy.stats
import pandas as pd



In [3]:
%matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns


## Mean Standard

loc =  parameter distribution 0
scale = standard defiasi nya 1

In [3]:
x = np.random.normal(loc=0,scale=1, size=10)

In [4]:
sum(x)/len(x)

-0.20272300990249398

In [5]:
np.mean(x)

-0.202723009902494

In [6]:
x.mean()

-0.202723009902494

In [7]:
pd.Series(x).mean()

-0.202723009902494

In [8]:
x

array([-0.48373161,  0.79931637,  0.03518984,  0.33564182, -0.31871038,
       -0.8962033 , -0.28454775, -1.03143772, -0.19414316,  0.01139579])

In [9]:
x[1] = np.nan

In [10]:
x

array([-0.48373161,         nan,  0.03518984,  0.33564182, -0.31871038,
       -0.8962033 , -0.28454775, -1.03143772, -0.19414316,  0.01139579])

Bagaimana jika ada data nan? pakai pandas series, pandas akan mengexclude nilai nan itu sendiri.

In [11]:
# awal
x.mean()

nan

In [12]:
pd.Series(x).mean()

-0.3140607190297749

## Median

In [13]:
x = np.random.normal(loc=0,scale=1, size=10)

In [14]:
x.mean()

0.13877919369967265

kalau di median kita menggunakan quantile
 .5 = dititik 0.5

In [15]:
np.quantile(x,.5)

0.098388095646466

In [16]:
statistics.median(x)

0.09838809564646599

In [17]:
np.median(x)

0.09838809564646599

In [18]:
pd.Series(x).median()

0.09838809564646599

## Mode / Modus

In [19]:
x_mode = [1,2,2,3,3,3,3,4,4,4,4]

In [20]:
statistics.mode(x_mode)

3

In [21]:
mode_scipy = scipy.stats.mode(x_mode)

C:\Users\Fadli Putra\AppData\Local\Temp\ipykernel_7920\481907955.py:1: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode_scipy = scipy.stats.mode(x_mode)


In [22]:
mode_scipy.mode

array([3])

In [23]:
pd.Series(x_mode).mode()

0    3
1    4
dtype: int64

## Mean

Geometri Mean

In [11]:
x = np.random.randint(1,10,10)
print(x)

[4 2 9 5 8 8 1 9 7 6]


In [13]:
x[-1] = 100

In [14]:
gmean = 1

for xi in x:
    gmean *= xi

gmean = gmean ** (1/len(x))
print(gmean)

6.5491102630555735


In [15]:
x.mean()

15.3

In [16]:
scipy.stats.gmean(x)

6.5491102630555735

Harmonic Mean

In [18]:
hmean = len(x) / sum(1/xi for xi in x)
print(hmean)

3.8833754546014925


In [19]:
hmean = scipy.stats.hmean(x)
print(hmean)

3.8833754546014916


In [22]:
x.sort()
x

array([  1,   2,   4,   5,   7,   8,   8,   9,   9, 100])

In [21]:
print('Mean: ', x.mean())
print('Gmain: ', gmean)
print('Hmean', hmean)

Mean:  15.3
Gmain:  6.5491102630555735
Hmean 3.8833754546014916


gmain = growth (pertumbuhan)
hmean = ratio (rasio)

# Measure of Spread

In [24]:
range = x.max() - x.min()
range

99

In [25]:
np.ptp(x)

99

In [29]:
Q1 = np.quantile(x,0.25)
Q3 = np.quantile(x,.75)

print("IQR", Q3-Q1)

IQR 4.5


In [30]:
np.quantile(x,0.975) - np.quantile(x,0.025)

78.30000000000004

# Spread

## Variance

In [31]:

x = np.random.random(100)

In [32]:
x.var()

0.08165761865448351

In [33]:
pd.Series(x).var()

0.08248244308533687

In [35]:
# standard deviasi
x.std()

0.2857579721626039

In [38]:
x.std(ddof=1)

0.2871975680352062

In [36]:
x.var()**0.5

0.2857579721626039

In [41]:
x.var(ddof=1)**0.5

0.2871975680352062

In [37]:
scipy.stats.median_abs_deviation(x)

0.2215130794428396

In [ ]:
1:08