## NumPy (Numerical Python)

In [ ]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.

Solving environment: ...working... done

# All requested packages already installed.

Retrieving notices: ...working... done




==> WARNING: A newer version of conda exists. <==
  current version: 22.9.0
  latest version: 23.1.0

Please update conda by running

    $ conda update -n base -c defaults conda




In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [3]:
print(a[0])

[1 2 3 4]


### creating array
np.array()
np.zeros()
np.ones()
np.empty()
np.arange()

In [7]:
import numpy as np

a = np.array([1,2,3])

In [5]:
a

array([1, 2, 3])

In [8]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [9]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [10]:
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [11]:
print(np.arange(4))
print(np.arange(0,10,2))
# (start, stop, step)

[0 1 2 3]
[0 2 4 6 8]


In [12]:
np.arange(2,29,5)

array([ 2,  7, 12, 17, 22, 27])

### add, remove and short
np.append() np.delete() np.sort()

In [13]:
arr = np.array([1,2,3,4,5,6,7,8])


In [14]:
np.append(arr, [1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [15]:
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8])

In [20]:
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8])

In [21]:
arr - np.array([2,1,5,3,7,4,6,8])

array([-1,  1, -2,  1, -2,  2,  1,  0])

In [22]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

### shape and size
ndarray.ndim() = jumlah dimensi array
nparray.size() = total elemen array 
ndarray.shape() = jumlah elemen yang disimpan disepanjang setiap dimensi array

In [27]:
array_example = np.array([[[0,1,2,3],
                           [4,5,6,7]],
                           
                           [[0,1,2,3],
                            [4,5,6,7]],

                            [[0,1,2,3,],
                             [4,5,6,7]]])

print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [28]:
array_example.ndim

3

In [29]:
array_example.size

24

In [30]:
array_example.shape

(3, 2, 4)

In [31]:
arr_one= np.array([[1,2,3,4,5]])

In [32]:
arr_one.ndim

2

In [33]:
arr_one.size

5

In [34]:
arr_one.shape

(1, 5)

### reshape
np.reshape() = memberikan bentuk baru ke array tanpa mengubah data

In [4]:
import numpy as np

In [5]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [6]:
b = a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [7]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

### convert 1D to 2D
np.newxis
np.expand_dims

In [8]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [9]:
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [10]:
row_vektor = a[np.newaxis, :]
print(row_vektor.shape)
print(row_vektor)

(1, 6)
[[1 2 3 4 5 6]]


In [11]:
col_vektor = a[:, np.newaxis]
print(col_vektor.shape)
print(col_vektor)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [12]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [13]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [14]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

### indexing and slicing

In [16]:
data = np.array([1,2,3])

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2])

[1 2 3]
1
2
[1 2]
[2 3]
2


In [17]:
a = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [19]:
five_up = (a >= 5)

print(a[five_up])
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [20]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


Pembatasan array

In [21]:
c = a[(a>2) & (a<11)]
print(c)

[ 3  4  5  6  7  8  9 10]


### creating array from existing data

slicing indexing --- np.vstack() --- np.hstack() --- np.hsplit() --- .view() --- .copy()

In [22]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])


In [23]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

Menumpuk dua array

In [2]:
import numpy as np

In [3]:
a_1 = np.array([[1,1],
      [2,2]])

In [4]:
a_2 = np.array([[3,3],
                [4,4]])

vertikal

In [5]:
np.vstack((a_1,a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

horizontal

In [6]:
np.hstack((a_1,a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [8]:
# array([[1,2,3,4,5,6,7,8,9,10,11,12],
#        [13,14,15,16,17,18,19,20,21,22,23,24]])

arrsplit = np.array([[1,2,3,4,5,6,7,8,9,10,11,12],
       [13,14,15,16,17,18,19,20,21,22,23,24]])

print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [11]:
np.hsplit(arrsplit,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

### shallow copy

In [12]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### basic array operations

In [15]:
a = np.array([1,2,3,4])
a.sum()

10

In [16]:
b = np.array([[1,1],[2,2]])
b

array([[1, 1],
       [2, 2]])

sum the rows

In [17]:
b.sum(axis=0)

array([3, 3])

sum the columns

In [18]:
b.sum(axis=1)

array([2, 4])

operations with data

In [19]:
data = np.array([1,2])
data

array([1, 2])

In [21]:
ones = np.ones(2)
ones

array([1., 1.])

In [22]:
data + ones

array([2., 3.])

In [23]:
data * data

array([1, 4])

In [27]:
data / data

array([1., 1.])

### broadcasting

In [28]:
data * 2

array([2, 4])

### more array operations

data.max() --- data.min() --- data.sum()

In [29]:
A = np.array([[0.7248426,0.19382948,0.08391839,0.49381039],
              [0.20391094, 0.18304082, 0.60294859, 0.59382938],
              [0.84902859, 0.28495011, 0.10384829, 0.18402948]
              ])
print(A)

[[0.7248426  0.19382948 0.08391839 0.49381039]
 [0.20391094 0.18304082 0.60294859 0.59382938]
 [0.84902859 0.28495011 0.10384829 0.18402948]]


In [30]:
A.sum()

4.50198706

In [31]:
A.min()

0.08391839

In [32]:
A.min(axis=0)

array([0.20391094, 0.18304082, 0.08391839, 0.18402948])

In [33]:
A.max()

0.84902859

In [34]:
A.max(axis=1)

array([0.7248426 , 0.60294859, 0.84902859])

In [35]:
A.std()

0.2521290033814608

### matrices

#### creating matrices

In [37]:
import numpy as np

In [41]:
np.ones((3,2))
np.zeros((3,2))
np.random.random((3,2))

array([[0.45379671, 0.3360535 ],
       [0.6061959 , 0.24321259],
       [0.59938875, 0.21451097]])

#### matrix arithmetic

In [42]:
data = np.array([[1,2], [3,4]])
print(data)

[[1 2]
 [3 4]]


In [43]:
ones = np.ones([2,2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [44]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [45]:
ones_row = np.ones([1,2])
print(ones_row)

[[1. 1.]]


In [46]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


#### dot product

In [49]:
a_1 = np.array([[1,2,3], [4,5,6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7,8], [9,10], [11,12]])
print(a_2)
print(a_2.shape)


[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [50]:
np.dot(a_1,a_2)

array([[ 58,  64],
       [139, 154]])

#### matrix indexing

In [55]:
data = np.array([[1,2],[3,4],[5,6]])

print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[0,1])
print(data[1:3])
print(data[0:2,1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


#### matrix aggregation

In [56]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [57]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [58]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


### transposing and reshaping

In [59]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [60]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [61]:
data_col = np.array([[1,2,3,4,5,6,]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [62]:
data_col.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
data_col.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [64]:
arr = np.arange(6).reshape((2,3))
print(arr)

[[0 1 2]
 [3 4 5]]


### N- dimensional array

In [65]:
ndarr = np.array([[[1,2],[3,4]],
                  [[5,6],[7,8]]])
print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [66]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [67]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [68]:
print(np.random.random((4,3,2)))

[[[0.66153905 0.16037952]
  [0.23508605 0.06564058]
  [0.12703075 0.1011262 ]]

 [[0.35572369 0.5288031 ]
  [0.63609846 0.48993773]
  [0.59371731 0.23714676]]

 [[0.95103939 0.97018181]
  [0.7139939  0.32235785]
  [0.60515091 0.77501027]]

 [[0.48455756 0.92996858]
  [0.1802031  0.37059219]
  [0.63201689 0.27856788]]]


### flatten n-dimensional array

In [69]:
arrflat = np.array ([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [70]:
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### working with math formulas

In [71]:
error = (1/n) * np.sum(np.square(observed - prediction))

NameError: name 'n' is not defined