### Numpy

In [1]:
import numpy as np

In [2]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [4]:
np.arange(0,1,0.02)

array([0.  , 0.02, 0.04, 0.06, 0.08, 0.1 , 0.12, 0.14, 0.16, 0.18, 0.2 ,
       0.22, 0.24, 0.26, 0.28, 0.3 , 0.32, 0.34, 0.36, 0.38, 0.4 , 0.42,
       0.44, 0.46, 0.48, 0.5 , 0.52, 0.54, 0.56, 0.58, 0.6 , 0.62, 0.64,
       0.66, 0.68, 0.7 , 0.72, 0.74, 0.76, 0.78, 0.8 , 0.82, 0.84, 0.86,
       0.88, 0.9 , 0.92, 0.94, 0.96, 0.98])

In [10]:
mylist = [3,2,3,5,6]
a = [3,2,3]
mylist.append([2,3])
mylist[-1]

[2, 3]

In [11]:
np.append(a, [2,3])

array([3, 2, 3, 2, 3])

In [12]:
np.delete(a, [1,2])

array([3])

In [33]:
arr = np.array([10,4,3,17,2,1,6,18])

In [34]:
np.sort(arr)

array([ 1,  2,  3,  4,  6, 10, 17, 18])

#### Shape and Size

In [35]:
arr2 = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

In [36]:
arr

array([10,  4,  3, 17,  2,  1,  6, 18])

In [37]:
arr.shape

(8,)

In [38]:
arr2.shape

(3, 4)

In [39]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Dimensi matrix

In [40]:
arr.ndim

1

In [41]:
arr2.ndim

2

In [42]:
print(arr)
print(arr.shape)

[10  4  3 17  2  1  6 18]
(8,)


In [43]:
arr_reshape = arr.reshape((2,4))

In [44]:
arr_reshape.ndim

2

In [45]:
arr.reshape(2,2,2)

array([[[10,  4],
        [ 3, 17]],

       [[ 2,  1],
        [ 6, 18]]])

In [49]:
arr[np.newaxis].shape

(1, 8)

In [55]:
arr.reshape(4,2)

array([[10,  4],
       [ 3, 17],
       [ 2,  1],
       [ 6, 18]])

In [56]:
arr[: , np.newaxis].shape

(8, 1)

In [64]:
np.expand_dims(arr, axis= 1)

array([[10],
       [ 4],
       [ 3],
       [17],
       [ 2],
       [ 1],
       [ 6],
       [18]])

#### Indexing and Slicing

In [72]:
mylist = [1,2,3,4,5,6,7]

In [73]:
mylist[1:4]

[2, 3, 4]

In [78]:
mylist[-3]

5

In [79]:
data  = [1,2,3,4,5,6,7]

In [80]:
data[1:4]

[2, 3, 4]

In [81]:
data[-2:]

[6, 7]

In [87]:
data[data%2 == 0]

TypeError: unsupported operand type(s) for %: 'list' and 'int'

In [82]:
data[(data > 3) & (data%2==0)]

TypeError: '>' not supported between instances of 'list' and 'int'

### Copy Array

In [88]:
arr

array([10,  4,  3, 17,  2,  1,  6, 18])

In [89]:
arr2 = arr.copy()

In [90]:
arr2 * 2

array([20,  8,  6, 34,  4,  2, 12, 36])

## Basic Operations

In [94]:
v1 = np.array([2,3,5])
v2 = np.array([1,2,3])

In [95]:
v1 * v2

array([ 2,  6, 15])

kalo axis 1 kesamping, axis 0 kebawah
0 = kolom
1 = baris

In [ ]:
data.sum()

In [96]:
v1

array([2, 3, 5])

In [100]:
v1 * 5

array([10, 15, 25])

### Matrix

In [104]:
# np.ones((3,3))
# np.zeros((3,3))
np.random.random((3,3))

array([[0.64502414, 0.00746137, 0.480824  ],
       [0.85990373, 0.41740919, 0.54316781],
       [0.54631582, 0.9539036 , 0.12164953]])

In [105]:
mat = np.array([
    [1,2],
    [3,4]
])

In [111]:
ones = np.ones((2,2))


In [112]:
mat + ones

array([[2., 3.],
       [4., 5.]])

In [113]:
mat + 5

array([[6, 7],
       [8, 9]])

In [114]:
mat * mat

array([[ 1,  4],
       [ 9, 16]])

In [116]:
np.matmul(mat,mat)

array([[ 7, 10],
       [15, 22]])

In [117]:
mat

array([[1, 2],
       [3, 4]])

In [118]:
np.dot(mat,mat)

array([[ 7, 10],
       [15, 22]])

### Transpose
Mengubah kolom jadi baris , baris jadi kolom

In [120]:
mat = np.array([
    [1,2],
    [3,4],
    [5,6]
])

In [121]:
mat.T

array([[1, 3, 5],
       [2, 4, 6]])

In [124]:
one_3d = np.random.random((3,3,3))

In [126]:
one_3d.shape

(3, 3, 3)

In [127]:
one_3d.reshape((27,))

array([0.80074977, 0.61553568, 0.34638221, 0.53115529, 0.93610982,
       0.59629557, 0.88267572, 0.86936412, 0.7216096 , 0.60606515,
       0.1010653 , 0.25044732, 0.52755553, 0.42665539, 0.17719544,
       0.43451706, 0.0141323 , 0.39712575, 0.13978461, 0.21364588,
       0.82965543, 0.05749661, 0.0703017 , 0.01550043, 0.32178149,
       0.15048522, 0.15421791])

In [128]:
one_3d.flatten()

array([0.80074977, 0.61553568, 0.34638221, 0.53115529, 0.93610982,
       0.59629557, 0.88267572, 0.86936412, 0.7216096 , 0.60606515,
       0.1010653 , 0.25044732, 0.52755553, 0.42665539, 0.17719544,
       0.43451706, 0.0141323 , 0.39712575, 0.13978461, 0.21364588,
       0.82965543, 0.05749661, 0.0703017 , 0.01550043, 0.32178149,
       0.15048522, 0.15421791])