### tips py day 4

#### notes on numpy vektor

In [1]:
import numpy as np

In [15]:
a = np.random.rand(5)

In [16]:
print(a)

[0.96512066 0.82511956 0.41029538 0.19913267 0.09590718]


In [17]:
a.shape

(5,)

In [18]:
print(a.T)

[0.96512066 0.82511956 0.41029538 0.19913267 0.09590718]


In [19]:
print(np.dot(a,a.T))

1.8294744860705832


In [20]:
a = np.random.rand(5,1)

print(a)

[[0.80577232]
 [0.63009105]
 [0.80474492]
 [0.03706952]
 [0.91031793]]


In [21]:
print(a.T)

[[0.80577232 0.63009105 0.80474492 0.03706952 0.91031793]]


In [22]:
print(np.dot(a,a.T))

[[0.64926903 0.50770993 0.64844118 0.02986959 0.73350899]
 [0.50770993 0.39701473 0.50706257 0.02335717 0.57358318]
 [0.64844118 0.50706257 0.64761438 0.02983151 0.73257372]
 [0.02986959 0.02335717 0.02983151 0.00137415 0.03374505]
 [0.73350899 0.57358318 0.73257372 0.03374505 0.82867873]]


In [23]:
a = np.random.rand(1,5)

In [24]:
print(a)

[[0.13010413 0.40131069 0.22480601 0.52248547 0.07408474]]
